name: Reusable GoReleaser CI workflow

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      distribution:
        required: true
        type: string

jobs:
  check-goreleaser:
    strategy:
      matrix:
        GOOS: [ linux]
        GOARCH: [amd64]
        exclude:
          - GOOS: darwin
            GOARCH: "386"
          - GOOS: darwin
            GOARCH: s390x
          - GOOS: windows
            GOARCH: arm64
          - GOOS: darwin
            GOARCH: arm
          - GOOS: windows
            GOARCH: arm
          - GOOS: windows
            GOARCH: s390x
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '~1.22.1'
          # architecture: ppc64le
          check-latest: true

      - name: Setup make
        run: sudo apt install -qy make
        
      - name: Generate the sources
        run: make generate-sources

      - name: Run GoReleaser for ${{ inputs.distribution }}
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser-pro
          version: latest
          workdir: distributions/${{ inputs.distribution }}
          args: --snapshot --clean --skip-sign --skip-sbom --timeout 2h --split
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
